import {useState,useEffect,useRef,useLayoutEffect} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Flame,LayoutDashboard,MapPinned,Building2,Wind,ChartNoAxesCombined,ChevronDown,ArrowUpRight,ArrowRight,Search,RefreshCw,SlidersHorizontal,X,Menu,Radio,CloudSun,Users,ShieldCheck,Clock,Database,ExternalLink,Info} from 'lucide-react';
import FireMap from './Map.jsx';
import {api,demoMode} from './api.js';
const navigation=[['overview','Vista general',LayoutDashboard],['fires','Incendios',Flame],['cities','Ciudades expuestas',Building2],['weather','Atmósfera',Wind],['risk','Riesgo de humo',ShieldCheck],['analytics','Analítica',ChartNoAxesCombined]];
const pageRoutes={overview:'/',fires:'/incendios',cities:'/ciudades',weather:'/atmosfera',risk:'/riesgo',analytics:'/analitica'};
const format=n=>new Intl.NumberFormat('es-PE').format(n || 0);
const Badge=({level})=><span className={`badge ${level?.toLowerCase()}`}>{level}</span>;
const Source=({value})=><span className={`source ${value==='api'?'connected':''}`}><i/>{({api:'API conectada',demo:'Datos demo',loading:'Consultando…',error:'Consulta fallida',configured:'API configurada'})[value] || 'Sin consultar'}</span>;
function useResource(loader,deps=[]){const [state,setState]=useState({data:null,loading:true,error:null,source:'loading'});const [version,setVersion]=useState(0);useEffect(()=>{let active=true;setState(s=>({...s,loading:true,error:null,source:'loading'}));loader().then(r=>active&&setState({...r,loading:false,error:null})).catch(e=>active&&setState({data:null,source:'error',loading:false,error:e.message}));return()=>{active=false;};},[...deps,version]);return {...state,reload:()=>setVersion(v=>v+1)};}
function ResourceState({resource,children}){if(resource.loading&&!resource.data)return <div className="empty"><RefreshCw className="spin" size={22}/> Cargando información…</div>;if(resource.error)return <div className="empty"><Info size={24}/><b>No pudimos consultar el servicio</b><span>{resource.error}</span><button className="button" onClick={resource.reload}>Reintentar</button></div>;if(Array.isArray(resource.data)&&!resource.data.length)return <div className="empty">No hay registros disponibles.</div>;return children;}
const detailLabels={max_frp:'Potencia radiativa (MW)',detection_count:'Puntos de calor',centroid_lat:'Latitud',centroid_lon:'Longitud',population:'Población',country:'País',name:'Nombre',level:'Nivel de riesgo',eta_hours:'Llegada estimada (horas)',last_detected_at:'Última detección',nearest_city:'Ciudad más cercana',risk_score:'Puntaje de riesgo',distance_km:'Distancia (km)',wind_speed_kmh:'Velocidad del viento (km/h)',wind_alignment:'Alineación del viento',sensitive_sites_count:'Sitios sensibles expuestos',sensitive_site_types:'Tipos de sitios sensibles'};
const siteTypeLabels={hospital:'Hospital',clinic:'Centro de salud',school:'Escuela',university:'Universidad',airport:'Aeropuerto',reserve:'Reserva o área protegida',fire_station:'Estación de bomberos',police_station:'Comisaría',care_home:'Residencia de cuidado',shelter:'Albergue',bus_terminal:'Terminal terrestre',port:'Puerto',power_station:'Subestación eléctrica',water_plant:'Planta de agua',market:'Mercado',industrial:'Zona industrial'};
function DetailValue({name,value}){if(name==='weather'&&value&&typeof value==='object')return <div className="weather-detail"><div><span>Ciudad</span><strong>{value.city_name||'—'}</strong></div><div><span>Temperatura</span><strong>{value.temperature_c==null?'—':`${value.temperature_c} °C`}</strong></div><div><span>Viento</span><strong>{value.wind_speed_kmh==null?'—':`${value.wind_speed_kmh} km/h`}</strong></div><div><span>Dirección</span><strong>{value.wind_direction_deg==null?'—':`${value.wind_direction_deg}°`}</strong></div><div><span>Humedad</span><strong>{value.humidity_pct==null?'—':`${value.humidity_pct}%`}</strong></div><div><span>PM2.5</span><strong>{value.pm25_ug_m3==null?'—':`${value.pm25_ug_m3} µg/m³`}</strong></div></div>;if(name==='nearest_city'&&value&&typeof value==='object')return <>{value.name||'—'}{value.distance_km==null?'':` · ${Number(value.distance_km).toFixed(1)} km`}</>;return <>{typeof value==='object'?JSON.stringify(value):String(value??'—')}</>;}
function Detail({selection,onClose,onEvaluateRisk}){
 const r=useResource(()=>selection.type==='fire'?api.fire(selection.id):selection.type==='city'?api.city(selection.id):selection.type==='weather'?api.cityWeather(selection.id):api.riskDetail(selection.id,selection.fireId),[selection.type,selection.id,selection.fireId]);
 const sites=useResource(()=>['city','risk'].includes(selection.type)?api.sensitiveSites(selection.id):Promise.resolve({data:[],source:'configured'}),[selection.type,selection.id]);
 useEffect(()=>{const onKey=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',onKey);const previous=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=old;previous?.focus();};},[onClose]);
 return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Detalle del registro" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Tab'){const items=e.currentTarget.querySelectorAll('button,a,[tabindex="0"]');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><div className="section-heading"><div><div className="eyebrow">EXPLORAR REGISTRO</div><h2>{selection.name || 'Detalle'}</h2></div><button autoFocus className="icon-button" aria-label="Cerrar detalle" onClick={onClose}><X/></button></div><Source value={r.source}/>{selection.type==='fire'&&<div className="detail-actions"><button className="button risk-action" onClick={()=>onEvaluateRisk(selection.id)}><ShieldCheck size={18}/> Evaluar riesgo de humo <ArrowRight size={16}/></button><p className="subtle">Consulta las ciudades expuestas a este incendio.</p></div>}<ResourceState resource={r}>{r.data&&<div className="detail-grid">{Object.entries(r.data).filter(([k])=>!['readings','_id'].includes(k)).map(([key,value])=><div className={key==='weather'?'detail-wide':undefined} key={key}><span>{detailLabels[key]||key.replaceAll('_',' ')}</span><strong><DetailValue name={key} value={value}/></strong></div>)}{r.data.readings&&<><h3>Historial meteorológico</h3>{r.data.readings.length?r.data.readings.map((w,i)=><div key={i}><span>{w.timestamp}</span><strong>{w.temperature_c??'—'} °C · Viento {w.wind_speed_kmh??'—'} km/h</strong></div>):<p>Sin lecturas disponibles.</p>}</>}</div>}</ResourceState>{['city','risk'].includes(selection.type)&&<section className="sensitive-sites"><div className="section-heading"><div><h3>Entornos sensibles</h3><p className="subtle">Lugares que requieren atención ante exposición al humo.</p></div><Source value={sites.source}/></div><ResourceState resource={sites}>{sites.data?.length?<div className="sensitive-site-list">{sites.data.map(item=><div className="sensitive-site" key={item.id}><span className="site-icon"><Building2 size={16}/></span><div><strong>{item.name}</strong><small>{siteTypeLabels[item.type]||item.type}</small></div></div>)}</div>:<p className="empty">No hay sitios sensibles registrados para esta ciudad.</p>}</ResourceState></section>}<p className="subtle mt-6">{r.source==='demo'?'Este registro es simulado para demostrar la experiencia de SmokeCast.':'Información devuelta por el microservicio configurado.'}</p></section></div>;
}
function CitiesCatalog({cities,onSelect}) {
 const [query,setQuery]=useState(''),[country,setCountry]=useState(''),[page,setPage]=useState(0);
 const normalize=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const countries=[...new Set(cities.map(c=>c.country))].sort((a,b)=>a.localeCompare(b,'es'));
 const filtered=cities.filter(c=>(!country||c.country===country)&&normalize(c.name).includes(normalize(query.trim())));
 const pageSize=48,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));
 const currentPage=Math.min(page,totalPages-1),rows=filtered.slice(currentPage*pageSize,(currentPage+1)*pageSize);
 return <>
  <div className="table-toolbar">
   <label className="search-box"><Search size={16}/><input type="search" aria-label="Buscar ciudad en todo el catálogo" placeholder="Buscar ciudad…" maxLength={120} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>
   <label className="filter-select"><SlidersHorizontal size={15}/><select aria-label="Filtrar ciudades por país" value={country} onChange={e=>{setCountry(e.target.value);setPage(0);}}><option value="">Todos los países</option>{countries.map(c=><option key={c} value={c}>{c}</option>)}</select></label>
   <CatalogPageControls page={currentPage} totalPages={totalPages} total={filtered.length} onChange={setPage}/>
  </div>
  <p className="subtle" role="status">{format(filtered.length)} localidades encontradas · {format(cities.length)} en el catálogo · {countries.length} países y territorios</p>
  <div className="city-grid">{rows.map(c=><button className="city-card" key={c.id} onClick={()=>onSelect({type:'city',id:c.id,name:c.name})}><Building2/><h3>{c.name}</h3><p>{c.country} · {c.population == null ? 'Población no disponible' : `${format(c.population)} habitantes`}</p><span>Explorar ciudad <ArrowRight size={16}/></span></button>)}</div>
  {!rows.length&&<p className="empty">No hay localidades que coincidan con la búsqueda.</p>}
  <div className="table-footer"><span>{filtered.length?currentPage*pageSize+1:0}–{Math.min((currentPage+1)*pageSize,filtered.length)} de {format(filtered.length)}</span><CatalogPageControls page={currentPage} totalPages={totalPages} total={filtered.length} onChange={setPage}/></div>
 </>;
}
function CatalogPageControls({page,totalPages,total,loading=false,error=null,onChange}) {
 const pages=Math.max(1,totalPages||0);
 return <div className="pagination catalog-pagination"><button className="button" disabled={loading||page===0} onClick={()=>onChange(page-1)}>Anterior</button><span>Página {page+1} de {pages} · {format(total)} resultados</span><button className="button" disabled={loading||!!error||page+1>=pages} onClick={()=>onChange(page+1)}>Siguiente</button></div>;
}
function PageControls({resource,page,onChange}) {
 const pages=Math.max(1,resource.pagination?.totalPages||0);
 return <CatalogPageControls page={page} totalPages={pages} total={resource.pagination?.totalElements??0} loading={resource.loading} error={resource.error} onChange={onChange}/>;
}
function WeatherPage({onSelect}) {
 const [page,setPage]=useState(0),[country,setCountry]=useState(''),[query,setQuery]=useState('');
 const r=useResource(()=>api.weatherOverview(page,country,query),[page,country,query]);
 return <><div className="section-heading"><div><h2>Atmósfera</h2><p className="subtle">Última lectura disponible por localidad. Explora todos los países.</p></div><button className="button" onClick={r.reload} disabled={r.loading}><RefreshCw size={15}/> Actualizar</button></div>
 <div className="card service-card"><Source value={r.source}/><div className="table-toolbar"><label className="search-box"><Search size={16}/><input type="search" aria-label="Buscar localidad en Atmósfera" placeholder="Buscar ciudad…" maxLength={120} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><label className="filter-select">País <select aria-label="País de las lecturas meteorológicas" value={country} onChange={e=>{setCountry(e.target.value);setPage(0);}}><option value="">Todos los países</option>{[...new Set([...(r.countries||[]),...(country?[country]:[])])].map(c=><option key={c}>{c}</option>)}</select></label><PageControls resource={r} page={page} onChange={setPage}/></div>
 <ResourceState resource={r}><div className="city-grid">{r.data?.map(w=><button className="city-card" key={w.city_id} onClick={()=>onSelect({type:'weather',id:w.city_id,name:w.city_name})}><CloudSun/><h3>{w.city_name}</h3><p>{w.city_country||'País no disponible'}</p><div className="temperature">{w.temperature_c??'—'}°<span>C</span></div><p>Viento: {w.wind_speed_kmh??'—'} km/h · {w.wind_direction_deg??'—'}°</p><p>{w.timestamp?new Date(w.timestamp).toLocaleString('es-PE'):'Fecha no disponible'}</p><span>Ver historial <ArrowRight size={16}/></span></button>)}</div></ResourceState>
 <div className="table-footer fire-pagination"><PageControls resource={r} page={page} onChange={setPage}/></div></div></>;
}
function RiskFirePicker({selectedFireId,onFireChange}) {
 const [page,setPage]=useState(0),[country,setCountry]=useState(''),[severity,setSeverity]=useState('');
 const countries=useResource(()=>api.fireCountries());
 const catalog=useResource(()=>api.fires(page,{country,severity}),[page,country,severity]);
 const options=catalog.data||[];
 const setFilter=(setter,value)=>{setter(value);setPage(0);onFireChange('');};
 return <div className="card service-card risk-picker"><h3>Selecciona el incendio a evaluar</h3><div className="table-toolbar">
 <label className="filter-select">País <select aria-label="País del incendio para riesgo" value={country} onChange={e=>setFilter(setCountry,e.target.value)}><option value="">Todos los países</option>{(countries.data||[]).map(c=><option key={c}>{c}</option>)}</select></label>
 <label className="filter-select">Intensidad del incendio <select aria-label="Intensidad del incendio para riesgo" value={severity} onChange={e=>setFilter(setSeverity,e.target.value)}><option value="">Todas las intensidades</option>{['Bajo','Moderado','Alto','Crítico'].map(s=><option key={s}>{s}</option>)}</select></label>
 {catalog.loading&&!catalog.data?<span className="control-loading"><RefreshCw className="spin" size={14}/> Cargando incendios…</span>:catalog.error?<span className="control-error">{catalog.error}</span>:<label className="select-wrap"><select aria-label="Seleccionar incendio para evaluar" value={selectedFireId||''} onChange={e=>onFireChange(e.target.value)}><option value="">Seleccionar incendio</option>{selectedFireId&&!options.some(f=>String(f.id)===String(selectedFireId))&&<option value={selectedFireId}>Incendio #{selectedFireId} · seleccionado</option>}{options.map(f=><option key={f.id} value={f.id}>#{f.id} · {f.country} · {f.level}</option>)}</select><ChevronDown size={14}/></label>}
 </div>{countries.error&&<p role="alert">{countries.error} <button className="button" onClick={countries.reload}>Reintentar países</button></p>}
 <div className="table-footer"><PageControls resource={catalog} page={page} onChange={setPage}/></div></div>;
}
function ServicePage(props) {
 return props.page==='weather'?<WeatherPage onSelect={props.onSelect}/>:<GeneralServicePage {...props}/>;
}
function AnalyticsPanel({resource}) {
 const [catalog,setCatalog]=useState(null),[selected,setSelected]=useState('fire_summary'),[country,setCountry]=useState(''),[query,setQuery]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(resource.source==='api'&&resource.data?.athena_enabled) api.analyticsReports().then(r=>setCatalog(r.data)).catch(e=>setError(e.message));},[resource.source,resource.data?.athena_enabled]);
 const run=async()=>{setBusy(true);setError('');setResult(null);try{const started=await api.analyticsQuery(selected,country);let state;for(let i=0;i<30;i++){state=await api.analyticsQueryStatus(started.data.query_id);if(['SUCCEEDED','FAILED','CANCELLED'].includes(state.data.status))break;await new Promise(resolve=>setTimeout(resolve,1000));}if(state?.data?.status!=='SUCCEEDED')throw new Error(state?.data?.reason||`La consulta terminó en estado ${state?.data?.status||'desconocido'}.`);const rows=await api.analyticsResults(started.data.query_id);setQuery(started.data.query_id);setResult(rows.data);}catch(e){setError(e.message);}finally{setBusy(false);}};
 if(resource.source==='demo') return <><div className="analytics-chart">{resource.data.summary?.map(row=><div className="bar-row" key={row.country}><span>{row.country}</span><div><i style={{width:`${row.detections/Math.max(1,...resource.data.summary.map(d=>d.detections))*100}%`}}/></div><strong>{format(row.detections)}</strong></div>)}</div><p className="subtle">Resumen simulado. Activa Athena para ejecutar consultas sobre S3.</p></>;
 if(!resource.data?.athena_enabled) return <p className="notice">MS5 está disponible, pero Athena está desactivado. Configura <code>ATHENA_ENABLED=true</code> y <code>ATHENA_OUTPUT_S3</code>.</p>;
 return <div className="analytics-panel"><div className="table-toolbar"><label className="filter-select">Consulta <select value={selected} onChange={e=>setSelected(e.target.value)}>{(catalog?.reports||[]).map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="filter-select">País <input aria-label="País para consulta Athena" value={country} maxLength={80} onChange={e=>setCountry(e.target.value)}/></label><button className="button" onClick={run} disabled={busy||!catalog}>{busy?'Consultando…':'Ejecutar consulta'}</button></div>{error&&<p className="control-error" role="alert">{error}</p>}{query&&<p className="subtle">Consulta {query} completada.</p>}{result&&<div className="table-scroll"><table><thead><tr>{result.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{result.rows.map((row,index)=><tr key={index}>{result.columns.map(column=><td key={column}>{row[column]??'—'}</td>)}</tr>)}</tbody></table></div>}</div>;
}
function GeneralServicePage({page,onSelect,selectedFireId,onFireChange}) {
 const r=useResource(()=>page==='risk'?(selectedFireId?api.risk(selectedFireId):Promise.resolve({data:null,source:'configured'})):({cities:api.cities,weather:api.weather,analytics:api.analytics}[page])(),[page,selectedFireId]);
 return <>
  <div className="section-heading"><div><h2>{navigation.find(n=>n[0]===page)?.[1]}</h2><p className="subtle">{({cities:'Explora el catálogo completo de ciudades y localidades. Busca por nombre o filtra por país.',weather:'Lecturas almacenadas de temperatura y viento.',risk:'Evalúa exposición por distancia, intensidad y dirección del viento.',analytics:'Estado de las consultas analíticas.'})[page]}</p></div>

   <button className="button" onClick={r.reload} disabled={r.loading}><RefreshCw size={15}/> Actualizar</button>
  </div>
  {page==='risk'&&<RiskFirePicker selectedFireId={selectedFireId} onFireChange={onFireChange}/>}
  <div className="card service-card"><Source value={r.source}/><ResourceState resource={r}>
   {page==='cities'&&r.data&&<CitiesCatalog cities={r.data} onSelect={onSelect}/>}

   {page==='risk'&&(!selectedFireId?<p className="empty">Selecciona un incendio para consultar las ciudades expuestas.</p>:r.data?.alerts?<>
    <p className="notice">{r.data.note} Las estimaciones demo no son alertas operativas.</p><p className="subtle risk-result-count">{r.data.alerts.length} {r.data.alerts.length===1?'ciudad expuesta':'ciudades expuestas'} encontradas para este incendio.</p>
    <div className="city-grid">{r.data.alerts.map(a=><button className="city-card" key={a.id} onClick={()=>onSelect({type:'risk',id:a.id,name:a.name,fireId:r.data.fire?.id})}><Badge level={a.level}/><h3>{a.name}</h3><p>Llegada estimada: {a.eta_hours == null ? 'No disponible' : `${a.eta_hours} h`}</p><p>{format(a.population)} habitantes</p><span>Ver evaluación <ArrowRight size={16}/></span></button>)}</div>
   </>:<>
    <p className="notice">{r.data?.note}</p>
    {r.data?.fire?<><h3>Ciudades cercanas al incendio #{r.data.fire.id}</h3>
     {r.data.nearby_cities.length?r.data.nearby_cities.map(c=><button className="near-city" key={c.id} onClick={()=>onSelect({type:'city',id:c.id,name:c.name})}>{c.name}<span>{c.distance_km == null ? 'Distancia no disponible' : `${c.distance_km.toFixed(1)} km`}</span></button>):<p className="empty">No hay ciudades dentro del radio consultado.</p>}
    </>:<p className="empty">No hay incendios disponibles para consultar ciudades cercanas.</p>}
   </>)}
   {page==='analytics'&&<>
    <AnalyticsPanel resource={r}/>
    <div className="analytics-status"><h3>Estado del servicio analítico</h3><p>{r.source==='demo'?'Demostración':r.data?.athena_enabled?'Disponible':'Pendiente de implementación'}</p><p className="subtle">{r.data?.note}</p></div>
   </>}
  </ResourceState></div>
 </>;
}
export default function App(){
 const location=useLocation(),navigate=useNavigate();
 const page=({'/':'overview','/incendios':'fires','/ciudades':'cities','/atmosfera':'weather','/riesgo':'risk','/analitica':'analytics'})[location.pathname] || 'overview';
 const [country,setCountry]=useState('Todos los países'),[query,setQuery]=useState(''),[severity,setSeverity]=useState('Todos'),[layer,setLayer]=useState('incendios'),[selection,setSelection]=useState(null),[mobile,setMobile]=useState(false),[help,setHelp]=useState(false),[riskFireId,setRiskFireId]=useState('');
 const [firePage,setFirePage]=useState(0);
 const countries=useResource(()=>api.fireCountries());
 const fires=useResource(()=>api.fires(firePage,{country:country==='Todos los países'?'':country,severity:severity==='Todos'?'':severity,q:query}),[firePage,country,severity,query]);
 const rows=fires.data||[];
 const footerRef=useRef(null),footerPosition=useRef(null);
 const changeFirePage=next=>{footerPosition.current=footerRef.current?.getBoundingClientRect().top??null;setFirePage(next);};
 useLayoutEffect(()=>{
  if(!fires.loading&&footerPosition.current!==null&&footerRef.current){
   const delta=footerRef.current.getBoundingClientRect().top-footerPosition.current;
   window.scrollBy({top:delta,behavior:'instant'});footerPosition.current=null;
  }
 },[fires.loading,fires.data]);
 const pagination=<div className="pagination"><button className="button" disabled={fires.loading||firePage===0} onClick={()=>changeFirePage(firePage-1)}>Anterior</button><span>Página {firePage+1} de {Math.max(1,fires.pagination?.totalPages||0)}</span><button className="button" disabled={fires.loading||!!fires.error||firePage+1>=(fires.pagination?.totalPages||0)} onClick={()=>changeFirePage(firePage+1)}>Siguiente</button></div>;

 const go=p=>{navigate(pageRoutes[p] || '/');setMobile(false);};
 const evaluateRisk=id=>{setRiskFireId(String(id));setSelection(null);go('risk');requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'instant'}));};
 return <div className="app-shell"><aside className={`sidebar ${mobile?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('overview');}}><span className="brand-symbol"><Flame size={25}/></span>SmokeCast<span className="brand-dot">.</span></a><div className="workspace-label">INTELIGENCIA AMBIENTAL</div><nav aria-label="Navegación principal">{navigation.map(([id,title,Icon])=><button key={id} className={`nav-item ${id} ${page===id?'active':''}`} onClick={()=>go(id)}><Icon size={19}/><span>{title}</span>{id==='fires'&&fires.data&&<span className="nav-count">{fires.pagination?.totalElements ?? fires.data.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="monitor-status"><span className="live-dot"/><span>Monitoreo ambiental</span><small>Sudamérica · UTC−5</small></div><button className="help-button" onClick={()=>setHelp(true)}><Info size={17}/> Acerca de SmokeCast <ArrowUpRight size={15}/></button></div></aside>{mobile&&<button className="sidebar-scrim" aria-label="Cerrar menú" onClick={()=>setMobile(false)}/>}
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}><Menu/></button><span>Plataforma</span><span className="slash">/</span><strong>{navigation.find(n=>n[0]===page)?.[1]}</strong></div><div className="topbar-right"><span className="region"><MapPinned size={14}/> Sudamérica</span><span className="topbar-divider"/><span className="team-avatar">SC</span></div></header>
 <main><div className="page-heading"><div><div className="eyebrow"><span className="tiny-line"/> OBSERVAR. ANTICIPAR. PROTEGER.</div><h1>{page==='overview'?'Una mirada al aire que nos rodea.':navigation.find(n=>n[0]===page)?.[1]}</h1><p>Inteligencia sobre incendios y humo para anticipar su impacto en nuestras ciudades.</p></div></div>
 {demoMode&&<div className="demo-banner"><span><span className="live-dot"/><strong>Modo demostración</strong><span className="demo-description">Explora SmokeCast con un escenario simulado del 12 sep. 2026.</span></span><button onClick={()=>setHelp(true)}>Ver información <ArrowUpRight size={14}/></button></div>}
 {(page==='overview'||page==='fires')?<><div className="stats-grid">{[{title:'Eventos de incendio',value:format(rows.length),icon:Flame,caption:'En la selección actual',color:'orange'},{title:'Puntos de calor',value:format(rows.reduce((s,f)=>s+f.detection_count,0)),icon:Radio,caption:'Detecciones satelitales agrupadas',color:'gold'},{title:'Eventos de alta intensidad',value:format(rows.filter(f=>['Crítico','Alto'].includes(f.level)).length),icon:ShieldCheck,caption:'Potencia radiativa superior a 90 MW',color:'red'},{title:'Países con detecciones',value:format(new Set(rows.map(f=>f.country).filter(c=>c!=='Sin país')).size),icon:MapPinned,caption:'Cobertura en Sudamérica',color:'green'}].map(s=><div className="stat-card" key={s.title}><div className="stat-top"><span>{s.title}</span><div className={`stat-icon ${s.color}`}><s.icon size={19}/></div></div><strong>{fires.loading?'—':fires.error?'—':s.value}</strong><div className="stat-caption"><span className={`small-dot ${s.color}`}/>{s.caption}</div></div>)}</div>
 <div className="monitor-grid"><section className="card map-card"><div className="section-heading"><div className="heading-with-icon"><MapPinned size={18}/><h2>Mapa de monitoreo</h2><span className="pill">Sudamérica</span></div><Source value={fires.source}/></div><div className="map-toolbar"><div className="segmented"><button className={layer==='incendios'?'selected':''} onClick={()=>setLayer('incendios')}><Flame size={14}/> Incendios</button><button className={layer==='humo'?'selected':''} onClick={()=>setLayer('humo')}><Wind size={15}/> Área ilustrativa</button></div><label className="select-wrap"><select aria-label="Filtrar por país" value={country} onChange={e=>{setCountry(e.target.value);setFirePage(0);}}>{['Todos los países',...(countries.data||[])].map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={14}/></label></div><ResourceState resource={fires}><FireMap fires={rows} layer={layer} onSelect={f=>setSelection({type:'fire',id:f.id,name:f.name})}/></ResourceState><div className="map-footer"><span><Info size={13}/> Selecciona un punto para explorar el incendio</span><span>Fuente: {fires.source==='demo'?'simulación':'Fire Catalog'}</span></div></section>
 <aside className="card priority-card"><div className="section-heading"><div><div className="eyebrow">EN EL RADAR</div><h2>Focos prioritarios</h2></div><span className="priority-symbol"><Flame size={19}/></span></div><p className="subtle">Eventos con mayor potencia radiativa en la selección.</p>{!rows.length?<p className="empty">Sin eventos para mostrar.</p>:[...rows].sort((a,b)=>b.max_frp-a.max_frp).slice(0,3).map((f,i)=><button className="priority-item" key={f.id} onClick={()=>setSelection({type:'fire',id:f.id,name:f.name})}><div className="priority-top"><span className="priority-index">0{i+1}</span><Badge level={f.level}/></div><h3>{f.name}<ArrowUpRight size={17}/></h3><p>{f.country}<span>{f.max_frp.toFixed(1)} <small>MW</small></span></p></button>)}<div className="priority-note"><ShieldCheck size={17}/><p>El nivel visual se basa en la intensidad del fuego. Consulta el riesgo de humo para explorar la exposición urbana.</p></div><button className="text-link" onClick={()=>go('risk')}>Explorar riesgo de humo <ArrowRight size={16}/></button></aside></div>
 {page==='fires'&&<section className="card events-card" aria-busy={fires.loading}><div className="section-heading"><div className="heading-with-icon"><h2>Eventos de incendio</h2><span className="pill">{rows.length} eventos</span></div><button className="text-link" onClick={fires.reload} disabled={fires.loading}><RefreshCw size={14} className={fires.loading?'spin':''}/> Actualizar</button></div><div className="table-toolbar"><label className="search-box"><Search size={16}/><input type="search" aria-label="Buscar incendios por ID o país" maxLength={100} placeholder="Buscar por ID o país…" value={query} onChange={e=>{setQuery(e.target.value);setFirePage(0);}}/>{query&&<button aria-label="Limpiar búsqueda" onClick={()=>{setQuery('');setFirePage(0);}}><X size={14}/></button>}</label><label className="filter-select"><SlidersHorizontal size={15}/><select aria-label="Filtrar intensidad" value={severity} onChange={e=>{setSeverity(e.target.value);setFirePage(0);}}>{['Todos','Crítico','Alto','Moderado','Bajo'].map(x=><option key={x} value={x}>{x==='Todos'?'Todas las intensidades':x}</option>)}</select></label></div><ResourceState resource={fires}><div className="table-scroll"><table><thead><tr><th>EVENTO / UBICACIÓN</th><th>PAÍS</th><th>INTENSIDAD</th><th>POTENCIA FRP <span>↗</span></th><th>DETECCIONES</th><th>ÚLTIMA DETECCIÓN</th><th/></tr></thead><tbody>{rows.map(f=><tr key={f.id}><td><div className="event-name"><span className={`event-icon ${f.level.toLowerCase()}`}><Flame size={17}/></span><div><button onClick={()=>setSelection({type:'fire',id:f.id,name:f.name})}>{f.name}</button><small>{f.centroid_lat.toFixed(3)}°, {f.centroid_lon.toFixed(3)}°</small></div></div></td><td>{f.country}</td><td><Badge level={f.level}/></td><td className="numeric">{f.max_frp.toFixed(1)} <span className="subtle">MW</span></td><td className="numeric">{f.detection_count}</td><td>{f.last_detected_at?new Date(f.last_detected_at).toLocaleString('es-PE',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'America/Lima'}):'—'}</td><td><button className="icon-button" aria-label={`Ver detalle de ${f.name}`} onClick={()=>setSelection({type:'fire',id:f.id,name:f.name})}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No hay eventos que coincidan con tus filtros.<button className="button" onClick={()=>{setQuery('');setCountry('Todos los países');setSeverity('Todos');setFirePage(0);}}>Limpiar filtros</button></div>}</div></ResourceState><div className="table-footer fire-pagination" ref={footerRef}><span>{rows.length} visibles · {fires.pagination?.totalElements ?? 0} resultados en todo el catálogo</span>{pagination}<span><Clock size={13}/> Horario de Lima (UTC−5)</span></div></section>}</>:<ServicePage key={page} page={page} onSelect={setSelection} selectedFireId={riskFireId} onFireChange={setRiskFireId}/>}
 <footer><span><Flame size={14}/> SmokeCast <span className="footer-dot">·</span> Datos que ayudan a ver más allá.</span></footer></main></div>
 {selection&&<Detail selection={selection} onClose={()=>setSelection(null)} onEvaluateRisk={evaluateRisk}/>}{help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Acerca de SmokeCast" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setHelp(false);if(e.key==='Tab')e.preventDefault();}}><div className="section-heading"><h2>Inteligencia ambiental, conectada.</h2><button autoFocus className="icon-button" aria-label="Cerrar información" onClick={()=>setHelp(false)}><X/></button></div><p>SmokeCast combina un catálogo de incendios, información urbana y lecturas atmosféricas para explorar la exposición al humo en Sudamérica.</p><div className="about-services">{['Fire Catalog · Incendios','Urban Exposure · Ciudades','Atmosphere Feed · Clima','Smoke Brain · Riesgo','Analytics Gateway · Analítica'].map((s,i)=><div key={s}><span><Database size={16}/> {s}</span><Source value={demoMode?'demo':'configured'}/></div>)}</div><p className="notice">Los datos de demostración son ficticios. Las áreas del mapa son ilustrativas y las estimaciones no deben utilizarse para tomar decisiones de emergencia.</p><p className="subtle">Las fuentes previstas son NASA FIRMS, GeoNames y Open-Meteo. La conexión a cada servicio se configura mediante las variables del proyecto.</p></section></div>}</div>;
}
